[ip] Dropping `Ipv4Endpoint and Port16`
demikernel/inetstack pull request #177
Opened 2022-05-30 14:27 UTC by ppenna

Description
-------------

This PR fixes https://github.com/demikernel/inetstack/issues/172.

Summary of Changes
------------------------
- Dropped `Port16` structure in favor of `u16`
- Dropped `Ipv4Endpoint` in favor of `std::net::SocketAddrV4`

Further Considerations
--------------------------
- https://github.com/demikernel/inetstack/issues/173 is related to this PR and shall be fixed next.
- https://github.com/demikernel/inetstack/issues/169 is related to this PR and shall be fixed next.

2022-06-01 21:24 UTC, BrianZill commented on src/protocols/udp/datagram/header.rs
> +    src_port: Option<u16>,
Get rid of the Option here (and everywhere else the src_port value is such); it is no longer needed.

2022-06-01 21:36 UTC, BrianZill commented on src/protocols/tcp/isn_generator.rs
>          digest.update(&remote_addr.to_be_bytes());
This was already rather silly (why byte swap before hashing when the hash is just for randomization?), now it is extra silly (why byte swap to convert into a host endian u32 and then byte swap it right back to network endian for the digest call?).  Just feed digest.update() the address octets directly.

Same for local_addr below.

2022-06-01 21:41 UTC, BrianZill requested changes
Looks good except for two things:

- Remove the Option type for the UDP source port.  Treat it as a straight u16, just like the destination port.
- There are two instances of an extraneous conversion of address bytes to a u32 (including byte-swapping) and back again in the IsnGenerator code.  Please remove them.

2022-06-02 13:52 UTC, ppenna commented on src/protocols/tcp/isn_generator.rs
>          digest.update(&remote_addr.to_be_bytes());
Nice catch.

2022-06-02 13:54 UTC, ppenna commented on src/protocols/udp/datagram/header.rs
> +    src_port: Option<u16>,
Thanks for pointing out this. Now we dropped unnecessary wrapping `Options` from IPv4 addresses as well.

2022-06-02 15:44 UTC, BrianZill commented on src/protocols/udp/datagram/header.rs
>          // Write source port. If not present, write zeros.
If you have a moment to fix this comment (just delete the "If not present, write zeros."), please do.

2022-06-02 17:50 UTC, BrianZill approved these changes
This looks good now, I'm really happy we're getting rid of these non-standard types that complicated things without really improving anything.  Thanks for doing this.

The one thing I don't understand about this PR is the OperationResult::Pop change, probably because I'm still not entirely clear about how futures work.  I'll ask you about this later though and not hold up this PR.

2022-06-02 17:51 UTC, ppenna commented on src/protocols/udp/datagram/header.rs
>          // Write source port. If not present, write zeros.
Sure. I'll fix this before merging.

2022-06-02 21:06 UTC, merged