[inetstack] Constructors should fail instead of panicking
demikernel/inetstack pull request #192
Opened 2022-07-23 01:38 UTC by justinvzyl

This PR fixes Issue #191 

The following peers' constructors panic on errors: `UdpPeer`, `Icmpv4Peer`, `Peer`, and `TcpPeer`. Instead of panicking, those peers' constructors should return a `Result<T, Fail>`

This PR:

    Removes the `panic!` from UdpPeer and Icmpv4Peer and instead returns an Err(Fail)
    Wraps the returned peer in an Ok(<Peer>) for UdpPeer, Icmpv4Peer, and TcpPeer
    Changes the signature of the constructors of UdpPeer, Icmpv4Peer, TcpPeer, and Peer to return Result<T, Fail> 
    Fixed up usage of these constructors in tests and in lib.rs to propagate the error

2022-07-25 12:23 UTC, ppenna requested changes
Thanks for this.

Looks good. We just need some minor corrections.

2022-07-25 12:23 UTC, ppenna commented on src/protocols/icmpv4/peer.rs
> +            None => return Err(Fail::new(EPERM, "failed to insert task in the scheduler")),
Could you apply the following changes on this?

- Change error code to `libc::EAGAIN`. This is the error code that we are using when we fail to insert co-routines in the scheduler. Once you do this, you can remove the import statement in line 67.
- Change the error message to be more descriptive, like we did in the ArpPeer. Something like "failed to schedule background co-routine for ICMPv4 module".

2022-07-25 12:23 UTC, ppenna commented on src/protocols/udp/peer.rs
> +            None => return Err(Fail::new(EPERM, "failed to insert task in the scheduler")),
Could you apply the following changes on this?

Change error code to libc::EAGAIN. This is the error code that we are using when we fail to insert co-routines in the scheduler. Once you do this, you can remove the import statement in line 67.
Change the error message to be more descriptive, like we did in the ArpPeer. Something like "failed to schedule background co-routine for ICMPv4 module".

2022-07-26 05:19 UTC, justinvzyl commented
@ppenna thank you for taking the time to review the PR. I have added your requested changes.

2022-07-26 10:39 UTC, ppenna reviewed
Looks good now. Thanks!

2022-07-26 10:40 UTC, ppenna approved these changes

2022-07-26 10:44 UTC, merged