[network] Enhancement: Support Windows build
demikernel/inetstack pull request #204
Opened 2022-08-28 21:17 UTC by anandbonde

Added support for building on Windows:

1. Changed makefile(s)
2. Used WinSock instead of libc for Windows

2022-08-29 16:50 UTC, ppenna requested changes

2022-08-29 16:50 UTC, ppenna commented on Makefile
> -# Runs regression tests.
Could you rollback this change?

2022-08-29 16:50 UTC, ppenna commented on Makefile
> -# Check code style formatting.
Could you rollback this change?

2022-08-29 16:50 UTC, ppenna commented on Makefile
> -# Check code style formatting for Rust.
Could you rollback this change?

2022-08-29 16:50 UTC, ppenna commented on Makefile
> -# Builds documentation.
Could you rollback this change?

2022-08-29 16:50 UTC, ppenna commented on Makefile
> -# Cleans up all build artifacts.
Could you rollback this change?

2022-08-29 16:50 UTC, ppenna commented on Makefile
> +	$(RM) Cargo.lock
Could you rollback the EOL change?

2022-08-29 16:50 UTC, ppenna commented on linux.mk
> +export FLAGS += --profile $(BUILD)
Could you rollback the EOL change?

2022-08-29 16:50 UTC, ppenna commented on src/lib.rs
> -    ///
Could you rollback this change.

2022-08-29 16:50 UTC, ppenna commented on src/lib.rs
> +        let addr_family = WinSock::ADDRESS_FAMILY(domain as u32);
Please be explicit about this type on the declaration as well.

2022-08-29 16:50 UTC, ppenna commented on src/lib.rs
> +                    Ok(qd)
No need for if else clause here. Could you please rewrite?

2022-08-29 16:50 UTC, ppenna commented on src/lib.rs
> +                    Ok(qd)
No need for if else clause here. Could you please rewrite?

2022-08-29 16:50 UTC, ppenna commented on tests/udp.rs
> +    let sockfd = create_socket(libos);
Could you please be specific about the type of this variable on declaration?

2022-08-29 16:50 UTC, ppenna commented on tests/udp.rs
> +    let sockfd = create_socket(libos);
Could you please be specific about the type of this variable on declaration?

2022-08-29 16:50 UTC, ppenna commented on tests/udp.rs
> +    let sockfd = create_socket(libos);
Could you please be specific about the type of this variable on declaration?

2022-09-02 17:59 UTC, BrianZill commented on src/lib.rs
> +    #[cfg(target_os = "windows")]
As I mentioned in the meeting, it would be preferable to have just one version of the socket function.  Since the only difference between the Linux and Windows versions are where certain constants come from, it would be better to just have the definitions of those constants be set by the platform-specific code.

2022-09-02 18:06 UTC, BrianZill commented on src/lib.rs
> +                    Ok(qd)
I think if we're going to have two versions of this function (which I don't recommend, see previous comment) that they shouldn't diverge more than necessary.  So, if you remove the if else clause here, I'd suggest removing it there as well.

2022-09-06 21:17 UTC, anandbonde commented
We discussed offline that we will hold on to any PRs on the inetstack repo until the "merge to a single repo" work moves ahead from the demikernel/inetstack/runtime point of view. I will send out another PR on the Demikernel repo once the move is complete.

2022-09-06 21:17 UTC, closed without merging